# Generated by Django 2.2.16 on 2022-02-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeIngridients', to='recipes.Ingredient', verbose_name='ingredients'),
        ),
    ]
