# Generated by Django 2.2.16 on 2022-02-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220209_0205'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='UniqueFavoriteEntry'),
        ),
    ]
