# Generated by Django 2.2.16 on 2022-02-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20220211_2232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngridients',
            new_name='RecipeIngridient',
        ),
        migrations.AddConstraint(
            model_name='recipeingridient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='UniqueRecipeIngridient'),
        ),
    ]
